name: quake
description: Sound to vibration
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.7.3
  audioplayers: ^0.18.3
  url_launcher: ^5.4.5
  flutter_volume_slider: ^1.0.6
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0
  fluttertoast: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/waveforms/
    - assets/songs/


  fonts:
    - family: Pangolin
      fonts:
        - asset: fonts/Pangolin-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf